- hosts: dns

  gather_facts: true
  remote_user: vagrant
  become: yes
  become_user: root
  become_method: sudo

  # Desactivar ejecución en paralelo para evitar problemas con Vagrant-Cachier
  serial: 1


  tasks:
    # Instalar BIND9
    - name: Instalar servicio DNS
      apt:
        name: bind9 
        state: present
      notify: start bind

    # Configuración general
    - name: Configurar named.conf.options
      copy: src=files/bind/named.conf.options
        dest=/etc/bind/named.conf.options
        owner=root group=root mode=0644
      notify: restart bind

    # Configurar resolvconf para utilizar nuestro DNS
    - name: Configurar resolvconf para utilizar nuestro DNS
      copy: src=files/bind/head
        dest=/etc/resolvconf/resolv.conf.d/head
        owner=root group=root mode=0644
      notify: update resolvconf


  handlers:
    - name: start bind
      service: name=bind9 state=started

    - name: restart bind
      service: name=bind9 state=restarted

    - name: update resolvconf
      command: resolvconf -u


