---

# Operaciones comunes sobre todos los nodos
- import_playbook: playbook/common.yml

# Configuración específica de los servidores DNS
- import_playbook: playbook/dns.yml

# Configuración específica de los servidores EMail
- import_playbook: playbook/email.yml

